### ISSUE TITLE
Målbild

### ISSUE THREAD

**Issue by itggot-david-lundholm** [itggot-kianoosh-geravesh/te4-slutspurt#1]
## Task:
- [ ] En dålig app som är medvetet sårbar för XSS och SQL-Injection med demonstrationer
- [ ] Ytterligare en version av samma app fast den är säkrad
- [x] ~Appen ska ha en databaslösning som bygger på ren SQL med PostgreSQL~
- [ ] Appens endpoints ska vara dokumenterade (YARDoc)
- [ ] Appen ska sträva efter 100% Test Coverage
- [ ] Utöver detta en TreeSort i C

## Tips:
- malloc och free
- struct
- gcc
